base_url = "https://um-arm-lab.github.io/lucca"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
favicon = false
large_card = true
footer_text = "This website is built using <a href='https://www.getzola.org' target='_blank'>Zola</a> and the <a href='http://github.com/aterenin/academic-paper/' target='_blank'>Academic Paper</a> theme, which is <a href='https://jeffhuang.com/designed_to_last/' target='_blank'>designed to last</a>."
server_side_katex = true